### ISSUE TITLE
TODO transferred from staged-recipes/libigt2

### ISSUE THREAD

**Issue by shadowwalkersb** [conda-forge/libgit2-feedstock#1]
Coped from https://github.com/conda-forge/staged-recipes/pull/1658#issue-179137529. Checkboxes checked in staged-recipes are crossed out here.

TODO before merging:
- License
  - [x] libgit2
  - [x] <del> pstdint.h (http://www.azillionmonkeys.com/qed/pstdint.h) </del> checked in staged-recipes
- [x] Add optional dependencies, https://github.com/libgit2/libgit2#optional-dependencies
  - [x] pthreads (non-Windows), addressed in ( https://github.com/conda-forge/libgit2-feedstock/issues/3 )
  - [x] <del>OpenSSL (non-Windows) </del> checked in staged-recipes
  - [x] LibSSH2, addressed in https://github.com/conda-forge/libgit2-feedstock/pull/2
  - [x] <del>iconv (OSX) </del> checked in staged-recipes
- [x] <del>Add tests </del> checked in staged-recipes

---

Per https://github.com/conda-forge/staged-recipes/pull/1658#issuecomment-251263011:
- [x] <del>`libiconv` is available on all platforms. Seems they only care about OS X. </del> checked in staged-recipes
- [x] <del>Having `openssl` working would be good. Need to [pin it](https://github.com/conda-forge/conda-forge.github.io/blob/68b2612a37a3a18bbebb04f08dee91e3fffb218e/scripts/pin_the_slow_way.py#L47) though. </del> checked in staged-recipes
- [x]     `libssh2` would be a very nice add.
- [x]     ... it looks like it requires [more thought](https://github.com/libgit2/libgit2/blob/master/THREADING.md#general-case). Maybe table it and raise an issue on the feedstock. addressed ( https://github.com/conda-forge/libgit2-feedstock/issues/3 )
- [x] <del>Please add `curl` if you haven't already. </del> checked in staged-recipes

**Comment by shadowwalkersb** [comment]
The items listed in the description have been raised as separate issues. If the license looks good, I am closing this issue.

**Comment by jakirkham** [comment]
License looks fine @shadowwalkersb . GPL2 with linking exception is pretty clear. As we distribute the license file in all packages too, people can look at that for more info if needed. Closing this sounds fine to me. 👍

**Comment by shadowwalkersb** [comment]
Thanks, @jakirkham !
